apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simulator
  name: simulator
  namespace: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
        actorSystemName: simulator
    spec:
      containers:
      - name: simulator
        image: alexs1986/device-simulator:latest
        # remove for real clusters, useful for minikube
        imagePullPolicy: Always
        ports:
        # akka-management and bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: device-simulator-internal-service
#  namespace: iot-system-1
#spec:
#  selector:
#    app: simulator  
#  ports:
#    - protocol: TCP
#      port: 30080
#      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simulator
  name: simulator-service
  namespace: simulator
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    nodePort: 31466
    port: 8558
    protocol: TCP
    targetPort: 8558
  - name: port-2
    nodePort: 31123
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simulator
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
